# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.mdiArea.setObjectName("mdiArea")
        self.horizontalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.imageCollectionController = QtWidgets.QDockWidget(MainWindow)
        self.imageCollectionController.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.imageCollectionController.setObjectName("imageCollectionController")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.dockWidgetContents)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setExpandsOnDoubleClick(False)
        self.verticalLayout.addWidget(self.treeWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.openCollectionButton = QtWidgets.QToolButton(self.dockWidgetContents)
        self.openCollectionButton.setObjectName("openCollectionButton")
        self.horizontalLayout_2.addWidget(self.openCollectionButton)
        self.newCollectionButton = QtWidgets.QToolButton(self.dockWidgetContents)
        self.newCollectionButton.setObjectName("newCollectionButton")
        self.horizontalLayout_2.addWidget(self.newCollectionButton)
        self.saveCollectionButton = QtWidgets.QToolButton(self.dockWidgetContents)
        self.saveCollectionButton.setObjectName("saveCollectionButton")
        self.horizontalLayout_2.addWidget(self.saveCollectionButton)
        self.closeCollectionButton = QtWidgets.QToolButton(self.dockWidgetContents)
        self.closeCollectionButton.setObjectName("closeCollectionButton")
        self.horizontalLayout_2.addWidget(self.closeCollectionButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.imageCollectionController.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.imageCollectionController)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Browser"))
        self.imageCollectionController.setWindowTitle(_translate("MainWindow", "Image Collection Controller"))
        self.openCollectionButton.setText(_translate("MainWindow", "Open"))
        self.newCollectionButton.setText(_translate("MainWindow", "New"))
        self.saveCollectionButton.setText(_translate("MainWindow", "Save"))
        self.closeCollectionButton.setText(_translate("MainWindow", "Close"))
